if: tag IS blank
sudo: false
language: go
go:
- 1.11.x
before_install:
- export VERSION=$(git describe --abbrev=0 --tags) && export LAST_PREFIX=$(cut -d'.'
  -f1,2 <<< $VERSION) && export LAST_SUFFIX=$(cut -d'.' -f3 <<< $VERSION) && export
  NEW_SUFFIX=$(expr "$LAST_SUFFIX" + 1) && export VERSION="$LAST_PREFIX.$NEW_SUFFIX"
install:
- go mod download
script:
- go test ./... -v
- GOOS=linux GOARCH=amd64 go build -ldflags="-X 'github.com/sonatype-nexus-community/cheque/buildversion.BuildVersion=$VERSION'
  -X 'github.com/sonatype-nexus-community/cheque/buildversion.BuildTime=$time' -X 'github.com/sonatype-nexus-community/cheque/buildversion.BuildCommit=$TRAVIS_COMMIT'"
  -o cheque-linux.amd64-$VERSION
- GOOS=darwin GOARCH=amd64 go build -ldflags="-X 'github.com/sonatype-nexus-community/cheque/buildversion.BuildVersion=$VERSION'
  -X 'github.com/sonatype-nexus-community/cheque/buildversion.BuildTime=$time' -X 'github.com/sonatype-nexus-community/cheque/buildversion.BuildCommit=$TRAVIS_COMMIT'"
  -o cheque-darwin.amd64-$VERSION
- GOOS=windows GOARCH=amd64 go build -ldflags="-X 'github.com/sonatype-nexus-community/cheque/buildversion.BuildVersion=$VERSION'
  -X 'github.com/sonatype-nexus-community/cheque/buildversion.BuildTime=$time' -X 'github.com/sonatype-nexus-community/cheque/buildversion.BuildCommit=$TRAVIS_COMMIT'"
  -o cheque-windows.amd64-$VERSION.exe

env:
- GO111MODULE=on
before_deploy:
- export TRAVIS_TAG=$VERSION
deploy:
  provider: releases
  api_key:
    secure: Up+Q9060KSR2UgJhxbQXiaYL40OZEkizxiCERmwNDzplwszUP/sU7D3a0Zau4FRsXTJi/jxdB9EOfjM6tdQNmKlnDNfnIAk+ge0cU9zDBXQbJUKedvNMB6Eb2cqUiahuw2kE07yqeemhRfC+FUCsW58iB8CXTJllXoy3GGfESsLxRJgIiasyGLzEJDNWC6wy5BXTIQfV0vYRFcCefMpKZxEdzavtItH4Odazi2p1iBMsQt4L36BOhlI+QD+LgwtyGy5JkEE/929DC85xrRtcgUhnt8MqyAuzO4miWQCbHQXjfS3fCdmoi+Ww24FUhNFdUSGHTMQzs8L7Or2UjAHPHEUpi3SUw2fhSiIT86MeOxZftTXTdJPKGvEnprsZ9uFp3Tje948/NT40lC+aY/Wh/ZYhkmtlh1zo4jxf8KDfY0OeZtA4Co9PrDR0vBckgus6OOJV24a9u5SRxXmybSthp0aoh/As6SKfVYB/YSCXAJUzWz096NP+CH40Ke+9N5SeKtHfw9+6sSVQaiSZpriqADzKXaT1xlQ23Eg5DJv19dKkwSUB/uu6OjwwM4he8qcyHjvsnrQ+azrQrmmf365j2czJ3XYlJxcW2BnnwGrtLwIsZeqX5Tt6cSQVts9VDCqrw9IpcXDcNM+wYaLuI2wgD9p09RKmL2clpxCOonGMGus=
  file: 
    - cheque-linux.amd64-$VERSION
    - cheque-darwin.amd64-$VERSION
    - cheque-windows.amd64-$VERSION.exe
  on:
    repo: sonatype-nexus-community/cheque
    all_branches: true
    condition: $TRAVIS_BRANCH = master && $TRAVIS_PULL_REQUEST = "false"
  skip_cleanup: true
  name: $VERSION
